### ISSUE TITLE
Using Seed Variable on Steam Market

### ISSUE THREAD

**Issue by iDEaXANA** [csgofloat/CSGOFloat-Extension#88]
Why can't i set the variable to a single value. You can only use >, < or <=, >= as far as i know. Or am i missing something? Thanks.

**Comment by Step7750** [comment]
Try `=` or `==`

**Comment by iDEaXANA** [comment]
Those were the first i tried. Tried to test it by equating it to the listings top of the list but they wouldn't filter out.  Any other ideas?

**Comment by Step7750** [comment]
`seed==586` works for me

**Comment by iDEaXANA** [comment]
K that's really weird lmao. Not sure why it didnt work the first time. cheers buddy!
